# -*- coding: utf-8 -*-
"""Classification_ML.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lnwN0NEDu7sFTxCaol8J1ycwzG3wGXUj
"""

import tensorflow as tf
import numpy as np
from tensorflow import keras
from tensorflow.keras.layers import Input, Conv1D, MaxPooling1D, Flatten
from tensorflow.keras.layers import Dense, concatenate
from tensorflow.keras.models import Model

#Import Ready-made data
data = np.genfromtxt("/content/drive/MyDrive/Capstone/synthetic_sensor_dataset_v2.csv",delimiter=',',skip_header=1)

X_sensor = data[:,0:2] #Sensor data
X_acc = data[:,2:302] #Accelerometer data
print(X_acc.shape)
X_acc = X_acc.reshape(-1,100,3) #Reshape to 100timesteps x 3 axes, '-1' calculates number of samples
Y = data[:,302:] #Labels

acc_shape = (100,3) #100 timesteps 3 axis
sensor_shape = (2,)

#Accelerometer (1DCNN)
acc_input = Input(shape=acc_shape) #1D Array Shape
acc_data = Conv1D(16,3,activation='relu')(acc_input)
acc_data = MaxPooling1D(2)(acc_data)
acc_data = Conv1D(32,3,activation='relu')(acc_data)
acc_data = MaxPooling1D(2)(acc_data)
acc_data = Flatten()(acc_data)

#Light and Temperature Sensor
sensor_input = Input(shape=sensor_shape)
sensor_data = Dense(16, activation='relu')(sensor_input)
sensor_data = Dense(8, activation='relu')(sensor_data)

#MLP on Merged Data
merged = concatenate([acc_data, sensor_data])
merged_data = Dense(32,activation='relu')(merged)
merged_data = Dense(16,activation='relu')(merged_data)

#Output Layer
output = Dense(5, activation='sigmoid')(merged_data)

model = Model(inputs=[acc_input,sensor_input], outputs=output)
model.compile(optimizer='adam',loss='binary_crossentropy', metrics=['accuracy'])

#Train Model
train_model = model.fit([X_acc,X_sensor], Y, epochs=2000, batch_size=32)
print('Final Accuracy:', train_model.history['accuracy'][-1])

#Save Model
model.save('ML_model.keras')

'''
#Convert Model to TensorFlow Lite
converter = tf.lite.TFLiteConverter.from_keras_model(model)
tflite_model = converter.convert()
with open('LWML_model.tflite', 'wb') as f:
    f.write(tflite_model)
'''